import { Noto_Sans_JP } from 'next/font/google';
import "./globals.css";
import Header from '@/components/Header';
import { NavigationMenu } from '@radix-ui/react-navigation-menu';
import { ThemeProvider } from "@/components/theme-provider"

const notoSans = Noto_Sans_JP({ subsets: ['latin']});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={notoSans.className}>
        <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
            <Header />
            {children}
          </ThemeProvider>
      </body>
    </html>
  )
}
